#include<iostream.h>
#include<conio.h>




void roll()
{


}

void calculate()
{


}


void frames()
{
cout << "ÉÍÍÑÍ»" << endl;
cout << "º  ³ º" << endl;
cout << "º  ÀÄ¶" << endl;
cout << "ÈÍÍÍÍ¼" << endl;

}

void main()
{

	clrscr();
	cout << "Bowling" << endl;
	cout << "1=Throw balls" << endl;
	cout << "2=Calculate Score" << endl;
	cout << "3=quit" << endl;
